# -*- coding: utf-8 -*-
"""ACCURACY ANALYSIS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-fUWKnfaaUXqeDtSAjyY3VnAWnUs1uN

WIND
"""

import matplotlib.pyplot as plt
import numpy as np
  
mape_wind = np.array([0.0323,0.0272,0.1161,0.1517])
year= np.array(['2018','2019','2020','2022'])
me_wind = np.array([0.1766,-0.0235,0.2776,-1.0108])
mae_wind = np.array([0.1766,0.2609,0.2776,1.0108])
mpe_wind = np.array([0.0323,-0.0014,0.1161,-0.1517])
rmse_wind = np.array([0.1834,0.2986,0.307,1.011])

plt.plot(year,mape_wind, marker = 'o',label = 'MAPE [0,1]')
plt.plot(year,me_wind,marker = 'o',label = 'ME [-inf,-inf]')
plt.plot(year,mae_wind,marker = 'o',label='MAE [0,inf]')
plt.plot(year,mpe_wind,marker = 'o',label = 'MPE [-inf,inf]')
plt.plot(year,rmse_wind,marker = 'o',label='RMSE [0,inf]')
plt.xlabel('YEAR')
plt.ylabel('ERROR PARAMTERS')
plt.title('WIND')
plt.legend(loc='lower left')
plt.show()

import matplotlib.pyplot as plt1
corr_wind = np.array([0.7333,0.7369,-0.9635,-0.2651])
accu_wind = np.array([0.9687,0.9734,0.8983,0.8483])
plt1.plot(year,corr_wind, marker = 'o',label='CORRELATION [-1,1]')
plt1.plot(year,accu_wind,marker = 'o',label = 'ACCURACY [0,1]')
plt1.xlabel('YEAR')
plt1.ylabel('corr and accuracy')
plt1.title('WIND')
plt1.legend(loc='lower left')
plt1.show()

"""SST"""

import matplotlib.pyplot as plt3
import numpy as np
  
mape_sst = np.array([0.0322,0.0176,0.0651,0.0255])
me_sst = np.array([0.7199,0.3292,1.2797,0.4349])
mae_sst = np.array([0.7199,0.3292,1.2797,0.5749])
mpe_sst = np.array([0.0322,0.0176,0.0651,0.0196])
rmse_sst = np.array([0.8647,0.3744,1.4841,0.7266])


plt3.plot(year,mape_sst, marker = 'o',label = 'MAPE [0,1]')
plt3.plot(year,me_sst,marker = 'o',label = 'ME [-inf,inf]')
plt3.plot(year,mae_sst,marker = 'o',label='MAE [0,inf]')
plt3.plot(year,mpe_sst,marker = 'o',label = 'MPE [-inf,inf]')
plt3.plot(year,rmse_sst,marker = 'o',label='RMSE [0,inf]')
plt3.xlabel('YEAR')
plt3.ylabel('ERROR PARAMTERS')
plt3.title('SST')
plt3.legend(loc='upper left')
plt3.show()

import matplotlib.pyplot as plt4
corr_sst = np.array([-0.9999,-0.9937,-0.9997,-0.9989])
accu_sst = np.array([0.9692,0.9828,0.9401,0.9755])
plt4.plot(year,corr_sst, marker = 'o',label='CORRELATION [-1,1]')
plt4.plot(year,accu_sst,marker = 'o',label = 'ACCURACY [0,1]')
plt4.xlabel('YEAR')
plt4.ylabel('corr and accuracy')
plt4.title('SST')
plt4.legend(loc='center')
plt4.show()